#!/usr/bin/env bash
set -euo pipefail

# Generated by analysis/phase2_preflight.py. Review before running.
# This file contains commands only; generation never launches experiments.

# Dataset: california
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/california.yaml --search-space configs/hpo/phase2/daf_moe_v2.yaml --best-output configs/experiments/phase2/daf_moe_v2/california_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/california.yaml --search-space configs/hpo/phase2/daf_moe_v2.yaml --best-config configs/experiments/phase2/daf_moe_v2/california_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/california.yaml --search-space configs/hpo/phase2/xgboost.yaml --best-output configs/experiments/phase2/xgboost/california_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/california.yaml --search-space configs/hpo/phase2/xgboost.yaml --best-config configs/experiments/phase2/xgboost/california_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/california.yaml --search-space configs/hpo/phase2/catboost.yaml --best-output configs/experiments/phase2/catboost/california_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/california.yaml --search-space configs/hpo/phase2/catboost.yaml --best-config configs/experiments/phase2/catboost/california_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/california.yaml --search-space configs/hpo/phase2/mlp.yaml --best-output configs/experiments/phase2/mlp/california_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/california.yaml --search-space configs/hpo/phase2/mlp.yaml --best-config configs/experiments/phase2/mlp/california_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/california.yaml --search-space configs/hpo/phase2/resnet.yaml --best-output configs/experiments/phase2/resnet/california_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/california.yaml --search-space configs/hpo/phase2/resnet.yaml --best-config configs/experiments/phase2/resnet/california_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/california.yaml --search-space configs/hpo/phase2/ft_transformer.yaml --best-output configs/experiments/phase2/ft_transformer/california_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/california.yaml --search-space configs/hpo/phase2/ft_transformer.yaml --best-config configs/experiments/phase2/ft_transformer/california_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/california.yaml --search-space configs/hpo/phase2/tabr.yaml --best-output configs/experiments/phase2/tabr/california_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/california.yaml --search-space configs/hpo/phase2/tabr.yaml --best-config configs/experiments/phase2/tabr/california_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/california.yaml --search-space configs/hpo/phase2/tabm.yaml --best-output configs/experiments/phase2/tabm/california_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/california.yaml --search-space configs/hpo/phase2/tabm.yaml --best-config configs/experiments/phase2/tabm/california_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/california.yaml --search-space configs/hpo/phase2/modernnca.yaml --best-output configs/experiments/phase2/modernnca/california_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/california.yaml --search-space configs/hpo/phase2/modernnca.yaml --best-config configs/experiments/phase2/modernnca/california_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/california.yaml --search-space configs/hpo/phase2/realmlp.yaml --best-output configs/experiments/phase2/realmlp/california_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/california.yaml --search-space configs/hpo/phase2/realmlp.yaml --best-config configs/experiments/phase2/realmlp/california_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/california.yaml --search-space configs/hpo/phase2/tabicl.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/california.yaml --search-space configs/hpo/phase2/tabm_ple.yaml --best-output configs/experiments/phase2/tabm_ple/california_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/california.yaml --search-space configs/hpo/phase2/tabm_ple.yaml --best-config configs/experiments/phase2/tabm_ple/california_best.yaml

# Dataset: adult
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/adult.yaml --search-space configs/hpo/phase2/daf_moe_v2.yaml --best-output configs/experiments/phase2/daf_moe_v2/adult_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/adult.yaml --search-space configs/hpo/phase2/daf_moe_v2.yaml --best-config configs/experiments/phase2/daf_moe_v2/adult_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/adult.yaml --search-space configs/hpo/phase2/xgboost.yaml --best-output configs/experiments/phase2/xgboost/adult_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/adult.yaml --search-space configs/hpo/phase2/xgboost.yaml --best-config configs/experiments/phase2/xgboost/adult_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/adult.yaml --search-space configs/hpo/phase2/catboost.yaml --best-output configs/experiments/phase2/catboost/adult_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/adult.yaml --search-space configs/hpo/phase2/catboost.yaml --best-config configs/experiments/phase2/catboost/adult_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/adult.yaml --search-space configs/hpo/phase2/mlp.yaml --best-output configs/experiments/phase2/mlp/adult_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/adult.yaml --search-space configs/hpo/phase2/mlp.yaml --best-config configs/experiments/phase2/mlp/adult_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/adult.yaml --search-space configs/hpo/phase2/resnet.yaml --best-output configs/experiments/phase2/resnet/adult_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/adult.yaml --search-space configs/hpo/phase2/resnet.yaml --best-config configs/experiments/phase2/resnet/adult_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/adult.yaml --search-space configs/hpo/phase2/ft_transformer.yaml --best-output configs/experiments/phase2/ft_transformer/adult_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/adult.yaml --search-space configs/hpo/phase2/ft_transformer.yaml --best-config configs/experiments/phase2/ft_transformer/adult_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/adult.yaml --search-space configs/hpo/phase2/tabr.yaml --best-output configs/experiments/phase2/tabr/adult_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/adult.yaml --search-space configs/hpo/phase2/tabr.yaml --best-config configs/experiments/phase2/tabr/adult_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/adult.yaml --search-space configs/hpo/phase2/tabm.yaml --best-output configs/experiments/phase2/tabm/adult_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/adult.yaml --search-space configs/hpo/phase2/tabm.yaml --best-config configs/experiments/phase2/tabm/adult_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/adult.yaml --search-space configs/hpo/phase2/modernnca.yaml --best-output configs/experiments/phase2/modernnca/adult_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/adult.yaml --search-space configs/hpo/phase2/modernnca.yaml --best-config configs/experiments/phase2/modernnca/adult_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/adult.yaml --search-space configs/hpo/phase2/realmlp.yaml --best-output configs/experiments/phase2/realmlp/adult_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/adult.yaml --search-space configs/hpo/phase2/realmlp.yaml --best-config configs/experiments/phase2/realmlp/adult_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/adult.yaml --search-space configs/hpo/phase2/tabicl.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/adult.yaml --search-space configs/hpo/phase2/tabm_ple.yaml --best-output configs/experiments/phase2/tabm_ple/adult_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/adult.yaml --search-space configs/hpo/phase2/tabm_ple.yaml --best-config configs/experiments/phase2/tabm_ple/adult_best.yaml

# Dataset: higgs_small
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/higgs_small.yaml --search-space configs/hpo/phase2/daf_moe_v2.yaml --best-output configs/experiments/phase2/daf_moe_v2/higgs_small_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/higgs_small.yaml --search-space configs/hpo/phase2/daf_moe_v2.yaml --best-config configs/experiments/phase2/daf_moe_v2/higgs_small_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/higgs_small.yaml --search-space configs/hpo/phase2/xgboost.yaml --best-output configs/experiments/phase2/xgboost/higgs_small_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/higgs_small.yaml --search-space configs/hpo/phase2/xgboost.yaml --best-config configs/experiments/phase2/xgboost/higgs_small_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/higgs_small.yaml --search-space configs/hpo/phase2/catboost.yaml --best-output configs/experiments/phase2/catboost/higgs_small_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/higgs_small.yaml --search-space configs/hpo/phase2/catboost.yaml --best-config configs/experiments/phase2/catboost/higgs_small_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/higgs_small.yaml --search-space configs/hpo/phase2/mlp.yaml --best-output configs/experiments/phase2/mlp/higgs_small_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/higgs_small.yaml --search-space configs/hpo/phase2/mlp.yaml --best-config configs/experiments/phase2/mlp/higgs_small_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/higgs_small.yaml --search-space configs/hpo/phase2/resnet.yaml --best-output configs/experiments/phase2/resnet/higgs_small_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/higgs_small.yaml --search-space configs/hpo/phase2/resnet.yaml --best-config configs/experiments/phase2/resnet/higgs_small_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/higgs_small.yaml --search-space configs/hpo/phase2/ft_transformer.yaml --best-output configs/experiments/phase2/ft_transformer/higgs_small_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/higgs_small.yaml --search-space configs/hpo/phase2/ft_transformer.yaml --best-config configs/experiments/phase2/ft_transformer/higgs_small_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/higgs_small.yaml --search-space configs/hpo/phase2/tabr.yaml --best-output configs/experiments/phase2/tabr/higgs_small_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/higgs_small.yaml --search-space configs/hpo/phase2/tabr.yaml --best-config configs/experiments/phase2/tabr/higgs_small_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/higgs_small.yaml --search-space configs/hpo/phase2/tabm.yaml --best-output configs/experiments/phase2/tabm/higgs_small_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/higgs_small.yaml --search-space configs/hpo/phase2/tabm.yaml --best-config configs/experiments/phase2/tabm/higgs_small_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/higgs_small.yaml --search-space configs/hpo/phase2/modernnca.yaml --best-output configs/experiments/phase2/modernnca/higgs_small_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/higgs_small.yaml --search-space configs/hpo/phase2/modernnca.yaml --best-config configs/experiments/phase2/modernnca/higgs_small_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/higgs_small.yaml --search-space configs/hpo/phase2/realmlp.yaml --best-output configs/experiments/phase2/realmlp/higgs_small_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/higgs_small.yaml --search-space configs/hpo/phase2/realmlp.yaml --best-config configs/experiments/phase2/realmlp/higgs_small_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/higgs_small.yaml --search-space configs/hpo/phase2/tabicl.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/higgs_small.yaml --search-space configs/hpo/phase2/tabm_ple.yaml --best-output configs/experiments/phase2/tabm_ple/higgs_small_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/higgs_small.yaml --search-space configs/hpo/phase2/tabm_ple.yaml --best-config configs/experiments/phase2/tabm_ple/higgs_small_best.yaml

# Dataset: covertype
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/covertype.yaml --search-space configs/hpo/phase2/daf_moe_v2.yaml --best-output configs/experiments/phase2/daf_moe_v2/covertype_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/covertype.yaml --search-space configs/hpo/phase2/daf_moe_v2.yaml --best-config configs/experiments/phase2/daf_moe_v2/covertype_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/covertype.yaml --search-space configs/hpo/phase2/xgboost.yaml --best-output configs/experiments/phase2/xgboost/covertype_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/covertype.yaml --search-space configs/hpo/phase2/xgboost.yaml --best-config configs/experiments/phase2/xgboost/covertype_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/covertype.yaml --search-space configs/hpo/phase2/catboost.yaml --best-output configs/experiments/phase2/catboost/covertype_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/covertype.yaml --search-space configs/hpo/phase2/catboost.yaml --best-config configs/experiments/phase2/catboost/covertype_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/covertype.yaml --search-space configs/hpo/phase2/mlp.yaml --best-output configs/experiments/phase2/mlp/covertype_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/covertype.yaml --search-space configs/hpo/phase2/mlp.yaml --best-config configs/experiments/phase2/mlp/covertype_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/covertype.yaml --search-space configs/hpo/phase2/resnet.yaml --best-output configs/experiments/phase2/resnet/covertype_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/covertype.yaml --search-space configs/hpo/phase2/resnet.yaml --best-config configs/experiments/phase2/resnet/covertype_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/covertype.yaml --search-space configs/hpo/phase2/ft_transformer.yaml --best-output configs/experiments/phase2/ft_transformer/covertype_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/covertype.yaml --search-space configs/hpo/phase2/ft_transformer.yaml --best-config configs/experiments/phase2/ft_transformer/covertype_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/covertype.yaml --search-space configs/hpo/phase2/tabr.yaml --best-output configs/experiments/phase2/tabr/covertype_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/covertype.yaml --search-space configs/hpo/phase2/tabr.yaml --best-config configs/experiments/phase2/tabr/covertype_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/covertype.yaml --search-space configs/hpo/phase2/tabm.yaml --best-output configs/experiments/phase2/tabm/covertype_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/covertype.yaml --search-space configs/hpo/phase2/tabm.yaml --best-config configs/experiments/phase2/tabm/covertype_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/covertype.yaml --search-space configs/hpo/phase2/modernnca.yaml --best-output configs/experiments/phase2/modernnca/covertype_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/covertype.yaml --search-space configs/hpo/phase2/modernnca.yaml --best-config configs/experiments/phase2/modernnca/covertype_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/covertype.yaml --search-space configs/hpo/phase2/realmlp.yaml --best-output configs/experiments/phase2/realmlp/covertype_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/covertype.yaml --search-space configs/hpo/phase2/realmlp.yaml --best-config configs/experiments/phase2/realmlp/covertype_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/covertype.yaml --search-space configs/hpo/phase2/tabicl.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/covertype.yaml --search-space configs/hpo/phase2/tabm_ple.yaml --best-output configs/experiments/phase2/tabm_ple/covertype_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/covertype.yaml --search-space configs/hpo/phase2/tabm_ple.yaml --best-config configs/experiments/phase2/tabm_ple/covertype_best.yaml

# Dataset: allstate
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/allstate.yaml --search-space configs/hpo/phase2/daf_moe_v2.yaml --best-output configs/experiments/phase2/daf_moe_v2/allstate_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/allstate.yaml --search-space configs/hpo/phase2/daf_moe_v2.yaml --best-config configs/experiments/phase2/daf_moe_v2/allstate_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/allstate.yaml --search-space configs/hpo/phase2/xgboost.yaml --best-output configs/experiments/phase2/xgboost/allstate_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/allstate.yaml --search-space configs/hpo/phase2/xgboost.yaml --best-config configs/experiments/phase2/xgboost/allstate_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/allstate.yaml --search-space configs/hpo/phase2/catboost.yaml --best-output configs/experiments/phase2/catboost/allstate_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/allstate.yaml --search-space configs/hpo/phase2/catboost.yaml --best-config configs/experiments/phase2/catboost/allstate_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/allstate.yaml --search-space configs/hpo/phase2/mlp.yaml --best-output configs/experiments/phase2/mlp/allstate_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/allstate.yaml --search-space configs/hpo/phase2/mlp.yaml --best-config configs/experiments/phase2/mlp/allstate_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/allstate.yaml --search-space configs/hpo/phase2/resnet.yaml --best-output configs/experiments/phase2/resnet/allstate_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/allstate.yaml --search-space configs/hpo/phase2/resnet.yaml --best-config configs/experiments/phase2/resnet/allstate_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/allstate.yaml --search-space configs/hpo/phase2/ft_transformer.yaml --best-output configs/experiments/phase2/ft_transformer/allstate_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/allstate.yaml --search-space configs/hpo/phase2/ft_transformer.yaml --best-config configs/experiments/phase2/ft_transformer/allstate_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/allstate.yaml --search-space configs/hpo/phase2/tabr.yaml --best-output configs/experiments/phase2/tabr/allstate_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/allstate.yaml --search-space configs/hpo/phase2/tabr.yaml --best-config configs/experiments/phase2/tabr/allstate_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/allstate.yaml --search-space configs/hpo/phase2/tabm.yaml --best-output configs/experiments/phase2/tabm/allstate_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/allstate.yaml --search-space configs/hpo/phase2/tabm.yaml --best-config configs/experiments/phase2/tabm/allstate_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/allstate.yaml --search-space configs/hpo/phase2/modernnca.yaml --best-output configs/experiments/phase2/modernnca/allstate_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/allstate.yaml --search-space configs/hpo/phase2/modernnca.yaml --best-config configs/experiments/phase2/modernnca/allstate_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/allstate.yaml --search-space configs/hpo/phase2/realmlp.yaml --best-output configs/experiments/phase2/realmlp/allstate_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/allstate.yaml --search-space configs/hpo/phase2/realmlp.yaml --best-config configs/experiments/phase2/realmlp/allstate_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/allstate.yaml --search-space configs/hpo/phase2/tabicl.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/allstate.yaml --search-space configs/hpo/phase2/tabm_ple.yaml --best-output configs/experiments/phase2/tabm_ple/allstate_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/allstate.yaml --search-space configs/hpo/phase2/tabm_ple.yaml --best-config configs/experiments/phase2/tabm_ple/allstate_best.yaml

# Dataset: bnp
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/bnp.yaml --search-space configs/hpo/phase2/daf_moe_v2.yaml --best-output configs/experiments/phase2/daf_moe_v2/bnp_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/bnp.yaml --search-space configs/hpo/phase2/daf_moe_v2.yaml --best-config configs/experiments/phase2/daf_moe_v2/bnp_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/bnp.yaml --search-space configs/hpo/phase2/xgboost.yaml --best-output configs/experiments/phase2/xgboost/bnp_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/bnp.yaml --search-space configs/hpo/phase2/xgboost.yaml --best-config configs/experiments/phase2/xgboost/bnp_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/bnp.yaml --search-space configs/hpo/phase2/catboost.yaml --best-output configs/experiments/phase2/catboost/bnp_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/bnp.yaml --search-space configs/hpo/phase2/catboost.yaml --best-config configs/experiments/phase2/catboost/bnp_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/bnp.yaml --search-space configs/hpo/phase2/mlp.yaml --best-output configs/experiments/phase2/mlp/bnp_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/bnp.yaml --search-space configs/hpo/phase2/mlp.yaml --best-config configs/experiments/phase2/mlp/bnp_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/bnp.yaml --search-space configs/hpo/phase2/resnet.yaml --best-output configs/experiments/phase2/resnet/bnp_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/bnp.yaml --search-space configs/hpo/phase2/resnet.yaml --best-config configs/experiments/phase2/resnet/bnp_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/bnp.yaml --search-space configs/hpo/phase2/ft_transformer.yaml --best-output configs/experiments/phase2/ft_transformer/bnp_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/bnp.yaml --search-space configs/hpo/phase2/ft_transformer.yaml --best-config configs/experiments/phase2/ft_transformer/bnp_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/bnp.yaml --search-space configs/hpo/phase2/tabr.yaml --best-output configs/experiments/phase2/tabr/bnp_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/bnp.yaml --search-space configs/hpo/phase2/tabr.yaml --best-config configs/experiments/phase2/tabr/bnp_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/bnp.yaml --search-space configs/hpo/phase2/tabm.yaml --best-output configs/experiments/phase2/tabm/bnp_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/bnp.yaml --search-space configs/hpo/phase2/tabm.yaml --best-config configs/experiments/phase2/tabm/bnp_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/bnp.yaml --search-space configs/hpo/phase2/modernnca.yaml --best-output configs/experiments/phase2/modernnca/bnp_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/bnp.yaml --search-space configs/hpo/phase2/modernnca.yaml --best-config configs/experiments/phase2/modernnca/bnp_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/bnp.yaml --search-space configs/hpo/phase2/realmlp.yaml --best-output configs/experiments/phase2/realmlp/bnp_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/bnp.yaml --search-space configs/hpo/phase2/realmlp.yaml --best-config configs/experiments/phase2/realmlp/bnp_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/bnp.yaml --search-space configs/hpo/phase2/tabicl.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/bnp.yaml --search-space configs/hpo/phase2/tabm_ple.yaml --best-output configs/experiments/phase2/tabm_ple/bnp_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/bnp.yaml --search-space configs/hpo/phase2/tabm_ple.yaml --best-config configs/experiments/phase2/tabm_ple/bnp_best.yaml

# Dataset: nhanes
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/nhanes.yaml --search-space configs/hpo/phase2/daf_moe_v2.yaml --best-output configs/experiments/phase2/daf_moe_v2/nhanes_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/nhanes.yaml --search-space configs/hpo/phase2/daf_moe_v2.yaml --best-config configs/experiments/phase2/daf_moe_v2/nhanes_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/nhanes.yaml --search-space configs/hpo/phase2/xgboost.yaml --best-output configs/experiments/phase2/xgboost/nhanes_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/nhanes.yaml --search-space configs/hpo/phase2/xgboost.yaml --best-config configs/experiments/phase2/xgboost/nhanes_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/nhanes.yaml --search-space configs/hpo/phase2/catboost.yaml --best-output configs/experiments/phase2/catboost/nhanes_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/nhanes.yaml --search-space configs/hpo/phase2/catboost.yaml --best-config configs/experiments/phase2/catboost/nhanes_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/nhanes.yaml --search-space configs/hpo/phase2/mlp.yaml --best-output configs/experiments/phase2/mlp/nhanes_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/nhanes.yaml --search-space configs/hpo/phase2/mlp.yaml --best-config configs/experiments/phase2/mlp/nhanes_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/nhanes.yaml --search-space configs/hpo/phase2/resnet.yaml --best-output configs/experiments/phase2/resnet/nhanes_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/nhanes.yaml --search-space configs/hpo/phase2/resnet.yaml --best-config configs/experiments/phase2/resnet/nhanes_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/nhanes.yaml --search-space configs/hpo/phase2/ft_transformer.yaml --best-output configs/experiments/phase2/ft_transformer/nhanes_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/nhanes.yaml --search-space configs/hpo/phase2/ft_transformer.yaml --best-config configs/experiments/phase2/ft_transformer/nhanes_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/nhanes.yaml --search-space configs/hpo/phase2/tabr.yaml --best-output configs/experiments/phase2/tabr/nhanes_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/nhanes.yaml --search-space configs/hpo/phase2/tabr.yaml --best-config configs/experiments/phase2/tabr/nhanes_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/nhanes.yaml --search-space configs/hpo/phase2/tabm.yaml --best-output configs/experiments/phase2/tabm/nhanes_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/nhanes.yaml --search-space configs/hpo/phase2/tabm.yaml --best-config configs/experiments/phase2/tabm/nhanes_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/nhanes.yaml --search-space configs/hpo/phase2/modernnca.yaml --best-output configs/experiments/phase2/modernnca/nhanes_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/nhanes.yaml --search-space configs/hpo/phase2/modernnca.yaml --best-config configs/experiments/phase2/modernnca/nhanes_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/nhanes.yaml --search-space configs/hpo/phase2/realmlp.yaml --best-output configs/experiments/phase2/realmlp/nhanes_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/nhanes.yaml --search-space configs/hpo/phase2/realmlp.yaml --best-config configs/experiments/phase2/realmlp/nhanes_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/nhanes.yaml --search-space configs/hpo/phase2/tabicl.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/nhanes.yaml --search-space configs/hpo/phase2/tabm_ple.yaml --best-output configs/experiments/phase2/tabm_ple/nhanes_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/nhanes.yaml --search-space configs/hpo/phase2/tabm_ple.yaml --best-config configs/experiments/phase2/tabm_ple/nhanes_best.yaml

# Dataset: mimic3
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/mimic3.yaml --search-space configs/hpo/phase2/daf_moe_v2.yaml --best-output configs/experiments/phase2/daf_moe_v2/mimic3_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/mimic3.yaml --search-space configs/hpo/phase2/daf_moe_v2.yaml --best-config configs/experiments/phase2/daf_moe_v2/mimic3_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/mimic3.yaml --search-space configs/hpo/phase2/xgboost.yaml --best-output configs/experiments/phase2/xgboost/mimic3_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/mimic3.yaml --search-space configs/hpo/phase2/xgboost.yaml --best-config configs/experiments/phase2/xgboost/mimic3_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/mimic3.yaml --search-space configs/hpo/phase2/catboost.yaml --best-output configs/experiments/phase2/catboost/mimic3_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/mimic3.yaml --search-space configs/hpo/phase2/catboost.yaml --best-config configs/experiments/phase2/catboost/mimic3_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/mimic3.yaml --search-space configs/hpo/phase2/mlp.yaml --best-output configs/experiments/phase2/mlp/mimic3_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/mimic3.yaml --search-space configs/hpo/phase2/mlp.yaml --best-config configs/experiments/phase2/mlp/mimic3_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/mimic3.yaml --search-space configs/hpo/phase2/resnet.yaml --best-output configs/experiments/phase2/resnet/mimic3_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/mimic3.yaml --search-space configs/hpo/phase2/resnet.yaml --best-config configs/experiments/phase2/resnet/mimic3_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/mimic3.yaml --search-space configs/hpo/phase2/ft_transformer.yaml --best-output configs/experiments/phase2/ft_transformer/mimic3_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/mimic3.yaml --search-space configs/hpo/phase2/ft_transformer.yaml --best-config configs/experiments/phase2/ft_transformer/mimic3_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/mimic3.yaml --search-space configs/hpo/phase2/tabr.yaml --best-output configs/experiments/phase2/tabr/mimic3_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/mimic3.yaml --search-space configs/hpo/phase2/tabr.yaml --best-config configs/experiments/phase2/tabr/mimic3_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/mimic3.yaml --search-space configs/hpo/phase2/tabm.yaml --best-output configs/experiments/phase2/tabm/mimic3_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/mimic3.yaml --search-space configs/hpo/phase2/tabm.yaml --best-config configs/experiments/phase2/tabm/mimic3_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/mimic3.yaml --search-space configs/hpo/phase2/modernnca.yaml --best-output configs/experiments/phase2/modernnca/mimic3_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/mimic3.yaml --search-space configs/hpo/phase2/modernnca.yaml --best-config configs/experiments/phase2/modernnca/mimic3_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/mimic3.yaml --search-space configs/hpo/phase2/realmlp.yaml --best-output configs/experiments/phase2/realmlp/mimic3_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/mimic3.yaml --search-space configs/hpo/phase2/realmlp.yaml --best-config configs/experiments/phase2/realmlp/mimic3_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/mimic3.yaml --search-space configs/hpo/phase2/tabicl.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/mimic3.yaml --search-space configs/hpo/phase2/tabm_ple.yaml --best-output configs/experiments/phase2/tabm_ple/mimic3_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/mimic3.yaml --search-space configs/hpo/phase2/tabm_ple.yaml --best-config configs/experiments/phase2/tabm_ple/mimic3_best.yaml

# Dataset: mimic4
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/mimic4.yaml --search-space configs/hpo/phase2/daf_moe_v2.yaml --best-output configs/experiments/phase2/daf_moe_v2/mimic4_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/mimic4.yaml --search-space configs/hpo/phase2/daf_moe_v2.yaml --best-config configs/experiments/phase2/daf_moe_v2/mimic4_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/mimic4.yaml --search-space configs/hpo/phase2/xgboost.yaml --best-output configs/experiments/phase2/xgboost/mimic4_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/mimic4.yaml --search-space configs/hpo/phase2/xgboost.yaml --best-config configs/experiments/phase2/xgboost/mimic4_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/mimic4.yaml --search-space configs/hpo/phase2/catboost.yaml --best-output configs/experiments/phase2/catboost/mimic4_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/mimic4.yaml --search-space configs/hpo/phase2/catboost.yaml --best-config configs/experiments/phase2/catboost/mimic4_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/mimic4.yaml --search-space configs/hpo/phase2/mlp.yaml --best-output configs/experiments/phase2/mlp/mimic4_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/mimic4.yaml --search-space configs/hpo/phase2/mlp.yaml --best-config configs/experiments/phase2/mlp/mimic4_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/mimic4.yaml --search-space configs/hpo/phase2/resnet.yaml --best-output configs/experiments/phase2/resnet/mimic4_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/mimic4.yaml --search-space configs/hpo/phase2/resnet.yaml --best-config configs/experiments/phase2/resnet/mimic4_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/mimic4.yaml --search-space configs/hpo/phase2/ft_transformer.yaml --best-output configs/experiments/phase2/ft_transformer/mimic4_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/mimic4.yaml --search-space configs/hpo/phase2/ft_transformer.yaml --best-config configs/experiments/phase2/ft_transformer/mimic4_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/mimic4.yaml --search-space configs/hpo/phase2/tabr.yaml --best-output configs/experiments/phase2/tabr/mimic4_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/mimic4.yaml --search-space configs/hpo/phase2/tabr.yaml --best-config configs/experiments/phase2/tabr/mimic4_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/mimic4.yaml --search-space configs/hpo/phase2/tabm.yaml --best-output configs/experiments/phase2/tabm/mimic4_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/mimic4.yaml --search-space configs/hpo/phase2/tabm.yaml --best-config configs/experiments/phase2/tabm/mimic4_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/mimic4.yaml --search-space configs/hpo/phase2/modernnca.yaml --best-output configs/experiments/phase2/modernnca/mimic4_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/mimic4.yaml --search-space configs/hpo/phase2/modernnca.yaml --best-config configs/experiments/phase2/modernnca/mimic4_best.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/mimic4.yaml --search-space configs/hpo/phase2/realmlp.yaml --best-output configs/experiments/phase2/realmlp/mimic4_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/mimic4.yaml --search-space configs/hpo/phase2/realmlp.yaml --best-config configs/experiments/phase2/realmlp/mimic4_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/mimic4.yaml --search-space configs/hpo/phase2/tabicl.yaml
python runners/run_phase2.py hpo --base-config configs/experiments/phase2/base/mimic4.yaml --search-space configs/hpo/phase2/tabm_ple.yaml --best-output configs/experiments/phase2/tabm_ple/mimic4_best.yaml
python runners/run_phase2.py final --base-config configs/experiments/phase2/base/mimic4.yaml --search-space configs/hpo/phase2/tabm_ple.yaml --best-config configs/experiments/phase2/tabm_ple/mimic4_best.yaml
