#!/usr/bin/env python
"""Phase 2 readiness gate and launch-command generator.

This script does not run HPO or final evaluation. It validates the fixed
protocol, configuration surface, local data, exact dependencies, and smoke
tests. READY_FOR_HPO is printed only when every check succeeds.
"""

import argparse
from importlib import metadata
import json
from pathlib import Path
import subprocess
import sys

import yaml


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.data.adapters import (  # noqa: E402
    ADAPTER_REGISTRY,
    DAFV2Adapter,
    ModernNCAAdapter,
    NativeRawAdapter,
    RTDLQuantileAdapter,
    TabMAdapter,
    TabMPLEAdapter,
    TabRAdapter,
)
from src.hpo.schema import load_search_space  # noqa: E402
from src.models.baselines.faiss_search import FAISS_DEPENDENCY  # noqa: E402
from src.native.dependencies import DEPENDENCIES, dependency_report  # noqa: E402
from src.phase2_execution import NATIVE_MODELS  # noqa: E402
from src.phase2_protocol import (  # noqa: E402
    DATASETS,
    FINAL_EVALUATION_SEEDS,
    HPO_SEED,
    MAIN_METHODS,
    MAIN_RANK_INCLUDED,
    N_HPO_COMPLETE_TRIALS,
    PROTOCOL_VERSION,
    SECONDARY_METHODS,
)


TUNABLE_METHODS = tuple(
    method for method in MAIN_METHODS + SECONDARY_METHODS if method != "tabicl"
)
ALL_METHODS = MAIN_METHODS + SECONDARY_METHODS
SEARCH_ROOT = ROOT / "configs/hpo/phase2"
BASE_ROOT = ROOT / "configs/experiments/phase2/base"
RETRIEVAL_SCALE_REPORT = (
    ROOT / "results/phase2/scale_smoke/reports/retrieval_scale_report.json"
)


def _read_yaml(path):
    with Path(path).open(encoding="utf-8") as file:
        return yaml.safe_load(file) or {}


def _base_hpo_command(dataset, model):
    best = f"configs/experiments/phase2/{model}/{dataset}_best.yaml"
    return (
        "python runners/run_phase2.py hpo "
        f"--base-config configs/experiments/phase2/base/{dataset}.yaml "
        f"--search-space configs/hpo/phase2/{model}.yaml "
        f'--best-output {best} --device "$DEVICE"'
    )


def _base_final_command(dataset, model):
    command = (
        "python runners/run_phase2.py final "
        f"--base-config configs/experiments/phase2/base/{dataset}.yaml "
        f"--search-space configs/hpo/phase2/{model}.yaml "
        '--device "$DEVICE"'
    )
    if model != "tabicl":
        command += (
            f" --best-config configs/experiments/phase2/{model}/{dataset}_best.yaml"
        )
    return command


def hpo_commands():
    commands = []
    for dataset in DATASETS:
        for model in TUNABLE_METHODS:
            log = f"logs/phase2/hpo/{dataset}_{model}.log"
            commands.append(
                f"run_hpo_job {log} {model} {_base_hpo_command(dataset, model)}"
            )
    return commands


def final_commands():
    commands = []
    for dataset in DATASETS:
        for model in ALL_METHODS:
            log = f"logs/phase2/final/{dataset}_{model}.log"
            commands.append(f"run_job {log} {_base_final_command(dataset, model)}")
    return commands


def launch_commands():
    """Deprecated combined command list retained for compatibility only."""
    return hpo_commands() + final_commands()


def _plan_header(kind):
    lines = [
        "#!/usr/bin/env bash",
        "set -uo pipefail",
        "",
        "# Generated by analysis/phase2_preflight.py.",
        f"# {kind} jobs only. Jobs continue independently after a failure.",
        'DEVICE="${DEVICE:-cuda:0}"',
        "failures=0",
        "",
        "run_job() {",
        '  local log="$1"',
        "  shift",
        '  mkdir -p "$(dirname "$log")"',
        '  if ! "$@" >"$log" 2>&1; then',
        '    printf "FAILED: %s (see %s)\\n" "$*" "$log" >&2',
        "    failures=$((failures + 1))",
        "  fi",
        "}",
    ]
    if kind == "HPO":
        lines.extend(
            [
                "",
                "run_hpo_job() {",
                '  local log="$1" model="$2"',
                "  shift 2",
                "  local ceiling_args=()",
                '  if [[ "$model" =~ ^(tabr|modernnca)$ && -n "${RETRIEVAL_COMPUTE_CEILING_HOURS:-}" ]]; then',
                '    ceiling_args=(--compute-ceiling-hours "$RETRIEVAL_COMPUTE_CEILING_HOURS")',
                "  fi",
                '  run_job "$log" "$@" "${ceiling_args[@]}"',
                "}",
            ]
        )
    lines.append("")
    return lines


def write_launch_plan(path, commands, kind):
    path = Path(path)
    if not path.is_absolute():
        path = ROOT / path
    lines = _plan_header(kind)
    lines.extend(commands)
    lines.extend(["", "exit $((failures > 0))"])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    path.chmod(0o755)
    return path, len(commands)


def write_deprecated_combined_plan(path):
    path = Path(path)
    if not path.is_absolute():
        path = ROOT / path
    path.write_text(
        "#!/usr/bin/env bash\n"
        'echo "Deprecated: use phase2_hpo_commands.sh, then '
        'phase2_final_commands.sh." >&2\n'
        "exit 2\n",
        encoding="utf-8",
    )
    path.chmod(0o755)
    return path


def _check_protocol(errors, checks):

    expected_seeds = tuple(range(43, 58))
    checks["protocol_version"] = PROTOCOL_VERSION
    checks["hpo_seed"] = HPO_SEED
    checks["final_seeds"] = list(FINAL_EVALUATION_SEEDS)
    checks["hpo_complete_trials"] = N_HPO_COMPLETE_TRIALS
    if HPO_SEED != 42:
        errors.append(f"HPO seed must be 42, got {HPO_SEED}.")
    if FINAL_EVALUATION_SEEDS != expected_seeds:
        errors.append("Final seed registry must be exactly 43..57.")
    if N_HPO_COMPLETE_TRIALS != 50:
        errors.append("HPO target must be 50 valid COMPLETE trials.")
    expected_main = {
        "daf_moe_v2",
        "xgboost",
        "catboost",
        "mlp",
        "resnet",
        "ft_transformer",
        "tabr",
        "tabm",
        "modernnca",
        "realmlp",
        "tabicl",
    }
    if set(MAIN_METHODS) != expected_main or len(MAIN_METHODS) != 11:
        errors.append("Main method registry is not the fixed set of 11 methods.")
    if SECONDARY_METHODS != ("tabm_ple",):
        errors.append("TabM PLE must be the only secondary method.")
    for method in ALL_METHODS:
        expected = method != "tabm_ple"
        if MAIN_RANK_INCLUDED.get(method) is not expected:
            errors.append(f"main-rank metadata mismatch for {method}.")


def _check_configs(errors, checks):
    expected_spaces = {f"{method}.yaml" for method in ALL_METHODS}
    actual_spaces = {path.name for path in SEARCH_ROOT.glob("*.yaml")}
    if actual_spaces != expected_spaces:
        errors.append(
            "Search-space files mismatch: "
            f"missing={sorted(expected_spaces - actual_spaces)}, "
            f"extra={sorted(actual_spaces - expected_spaces)}."
        )
    parsed = {}
    for method in ALL_METHODS:
        path = SEARCH_ROOT / f"{method}.yaml"
        if not path.exists():
            continue
        try:
            space = load_search_space(path)
        except Exception as exc:
            errors.append(f"Invalid search space {path}: {exc}")
            continue
        parsed[method] = space.schema_hash
        if space.model_name != method:
            errors.append(f"{path} routes to {space.model_name}, expected {method}.")
        if space.rank_included is not MAIN_RANK_INCLUDED[method]:
            errors.append(f"{path} rank_included is inconsistent with protocol.")
        if method == "tabicl" and space.search:
            errors.append("TabICLv2 must not expose an HPO search section.")
        if method != "tabicl" and not space.search:
            errors.append(f"Tunable method {method} has no search parameters.")
    checks["search_space_hashes"] = parsed

    base_records = {}
    for dataset in DATASETS:
        base_path = BASE_ROOT / f"{dataset}.yaml"
        if not base_path.exists():
            errors.append(f"Missing base config: {base_path.relative_to(ROOT)}")
            continue
        base = _read_yaml(base_path)
        missing = sorted(
            {"data_config_path", "task_type", "optimize_metric"}.difference(base)
        )
        if missing:
            errors.append(f"{base_path} is missing {missing}.")
            continue
        data_path = ROOT / base["data_config_path"]
        if not data_path.exists():
            errors.append(f"Missing dataset config: {base['data_config_path']}")
            continue
        data = _read_yaml(data_path)
        csv_path = ROOT / data.get("csv_path", "")
        if not csv_path.is_file():
            errors.append(f"Missing raw CSV for {dataset}: {csv_path}")
        base_records[dataset] = {
            "task_type": base["task_type"],
            "metric": base["optimize_metric"],
            "data_config": base["data_config_path"],
            "csv": str(csv_path.relative_to(ROOT))
            if csv_path.exists()
            else str(csv_path),
        }
    checks["datasets"] = base_records


def _check_routing(errors, checks):
    expected_adapters = {
        "daf_moe_v2": DAFV2Adapter,
        "mlp": RTDLQuantileAdapter,
        "resnet": RTDLQuantileAdapter,
        "ft_transformer": RTDLQuantileAdapter,
        "tabr": TabRAdapter,
        "tabm": TabMAdapter,
        "tabm_ple": TabMPLEAdapter,
        "modernnca": ModernNCAAdapter,
        "xgboost": NativeRawAdapter,
        "catboost": NativeRawAdapter,
        "realmlp": NativeRawAdapter,
        "tabicl": NativeRawAdapter,
    }
    for model, expected in expected_adapters.items():
        actual = ADAPTER_REGISTRY.get(model)
        if actual is not expected:
            errors.append(
                f"Adapter routing mismatch for {model}: "
                f"{getattr(actual, '__name__', actual)} != {expected.__name__}."
            )
    if NATIVE_MODELS != frozenset({"xgboost", "catboost", "realmlp", "tabicl"}):
        errors.append("Native execution registry does not match the protocol.")
    native_sources = [
        ROOT / "src/native/data.py",
        ROOT / "src/native/runner.py",
        ROOT / "src/native/estimators.py",
        ROOT / "runners/run_phase2_native.py",
    ]
    for path in native_sources:
        if "DAFPreprocessor" in path.read_text(encoding="utf-8"):
            errors.append(f"Native path imports or mentions DAFPreprocessor: {path}")
    checks["adapter_routing"] = {
        model: adapter.__name__ for model, adapter in expected_adapters.items()
    }


def _installed_version(distribution):
    try:
        return metadata.version(distribution)
    except metadata.PackageNotFoundError:
        return None


def _check_dependencies(errors, checks):
    python_version = (
        f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}"
    )
    checks["python_version"] = python_version
    if sys.version_info[:2] < (3, 10):
        errors.append(
            f"Phase 2 requires Python >=3.10 for the full model set; current={python_version}."
        )

    optuna = _installed_version("optuna")
    checks["optuna"] = {"required": "4.9.0", "installed": optuna}
    if optuna != "4.9.0":
        errors.append(
            f"Optuna pin mismatch: installed={optuna}, required=4.9.0. "
            "Run: python -m pip install 'optuna==4.9.0'"
        )

    native = {}
    for model in DEPENDENCIES:
        report = dependency_report(model)
        native[model] = report
        if not report["compatible"]:
            errors.append(
                f"{model} dependency is not ready: installed="
                f"{report['installed_version']}, required={report['required_version']}, "
                f"python>={report['minimum_python']}. Run: {report['install_command']}"
            )
    checks["native_dependencies"] = native

    faiss_required = FAISS_DEPENDENCY.split("==", 1)[1]
    faiss_installed = _installed_version("faiss-gpu-cu12")
    checks["faiss"] = {
        "required": faiss_required,
        "installed": faiss_installed,
    }
    if faiss_installed != faiss_required:
        errors.append(
            f"FAISS pin mismatch: installed={faiss_installed}, "
            f"required={faiss_required}."
        )

    requirements = (ROOT / "requirements.txt").read_text(encoding="utf-8")
    required_lines = ["optuna==4.9.0", FAISS_DEPENDENCY] + [
        spec.requirement for spec in DEPENDENCIES.values()
    ]
    for requirement in required_lines:
        if requirement not in requirements:
            errors.append(f"requirements.txt is missing exact pin: {requirement}")


def _retrieval_timeout_only(report):
    combinations = report.get("combinations", [])
    if not combinations:
        return False
    saw_timeout = False
    for item in combinations:
        stage1 = item.get("stage1", {})
        stage2 = item.get("stage2", {})
        memory = stage1.get("memory", {})
        training = stage1.get("training", {})
        if (
            stage1.get("status") != "PASS"
            or training.get("finite") is not True
            or memory.get("oom") is True
        ):
            return False
        stage2_status = stage2.get("status")
        if stage2_status == "TIMEOUT":
            saw_timeout = True
        elif stage2_status != "PASS":
            return False
    return saw_timeout


def _check_retrieval_scale(errors, warnings, checks):
    relative_path = str(RETRIEVAL_SCALE_REPORT.relative_to(ROOT))
    if not RETRIEVAL_SCALE_REPORT.is_file():
        checks["retrieval_scale"] = {
            "report": relative_path,
            "decision": "MISSING",
        }
        errors.append(
            "Retrieval scale report is missing; TabR/ModernNCA production HPO "
            "must remain blocked."
        )
        return
    try:
        report = json.loads(RETRIEVAL_SCALE_REPORT.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        errors.append(f"Invalid retrieval scale report: {exc}")
        return
    decision = report.get("decision")
    blockers = list(report.get("blockers", []))
    timeout_only = _retrieval_timeout_only(report)
    checks["retrieval_scale"] = {
        "report": relative_path,
        "decision": decision,
        "protocol_version": report.get("protocol_version"),
        "blockers": blockers,
        "timeout_only_warning": timeout_only,
        "cost_estimate": report.get("cost_estimate"),
        "production_experiments_started": report.get("production_experiments_started"),
    }
    if report.get("protocol_version") != PROTOCOL_VERSION:
        errors.append(
            "Retrieval scale report protocol does not match the active protocol."
        )
    if report.get("production_experiments_started") is not False:
        errors.append(
            "Retrieval scale report does not confirm production experiments stayed off."
        )
    if decision == "READY_FOR_HPO":
        return
    detail = "; ".join(blockers) if blockers else "no blocker detail recorded"
    if timeout_only:
        warnings.append(
            "Retrieval scale timeout warning (cost estimates are lower bounds): "
            + detail
        )
    else:
        errors.append(f"Retrieval scale gate is {decision}: {detail}")


def _run_command(command):

    completed = subprocess.run(
        command,
        cwd=str(ROOT),
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )
    output = completed.stdout.strip()
    tail = "\n".join(output.splitlines()[-20:])
    return {
        "command": " ".join(command),
        "returncode": completed.returncode,
        "output_tail": tail,
    }


def _check_tests(errors, checks):
    commands = (
        [sys.executable, "-m", "unittest", "discover", "-s", "tests", "-v"],
        [sys.executable, "analysis/verify_baselines.py"],
        [sys.executable, "analysis/verify_v2_architecture.py"],
        [sys.executable, "analysis/verify_v15_equivalence.py"],
        [sys.executable, "analysis/verify_phase2_native_models.py"],
    )
    results = []
    for command in commands:
        result = _run_command(command)
        results.append(result)
        if result["returncode"] != 0:
            errors.append(
                f"Verification failed ({result['command']}):\n{result['output_tail']}"
            )
    checks["test_runs"] = results


def _write_report(
    path,
    checks,
    errors,
    warnings,
    hpo_plan,
    hpo_count,
    final_plan,
    final_count,
    tests_skipped,
):
    ready = not errors
    readiness = (
        "PHASE2_NOT_READY"
        if errors
        else ("READY_FOR_HPO_WITH_RETRIEVAL_WARNING" if warnings else "READY_FOR_HPO")
    )
    payload = {
        "protocol_version": PROTOCOL_VERSION,
        "ready_for_hpo": ready,
        "readiness": readiness,
        "tests_skipped": bool(tests_skipped),
        "launch_plans": {
            "hpo": str(hpo_plan.relative_to(ROOT)),
            "hpo_command_count": hpo_count,
            "final": str(final_plan.relative_to(ROOT)),
            "final_command_count": final_count,
        },
        "checks": checks,
        "warnings": warnings,
        "blockers": errors,
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(payload, indent=2, sort_keys=True, default=str) + "\n",
        encoding="utf-8",
    )
    return path


def parse_args(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--skip-tests",
        action="store_true",
        help="Skip executable tests. This always prevents a READY result.",
    )
    parser.add_argument(
        "--hpo-launch-plan",
        default="scripts/phase2_hpo_commands.sh",
        help="Generated HPO-only command file.",
    )
    parser.add_argument(
        "--final-launch-plan",
        default="scripts/phase2_final_commands.sh",
        help="Generated final-only command file.",
    )
    parser.add_argument(
        "--deprecated-combined-plan",
        default="scripts/phase2_launch_commands.sh",
        help="Deprecated combined path replaced with a fail-fast notice.",
    )
    parser.add_argument(
        "--report",
        default="results/phase2/preflight_report.json",
        help="Machine-readable preflight report.",
    )
    return parser.parse_args(argv)


def main(argv=None):
    args = parse_args(argv)
    errors = []
    warnings = []
    checks = {}
    _check_protocol(errors, checks)
    _check_configs(errors, checks)
    _check_routing(errors, checks)
    _check_dependencies(errors, checks)
    _check_retrieval_scale(errors, warnings, checks)

    hpo_plan, hpo_count = write_launch_plan(args.hpo_launch_plan, hpo_commands(), "HPO")
    final_plan, final_count = write_launch_plan(
        args.final_launch_plan, final_commands(), "FINAL"
    )
    deprecated_plan = write_deprecated_combined_plan(args.deprecated_combined_plan)
    if hpo_count != 99:
        errors.append(f"HPO plan contains {hpo_count} commands, expected 99.")
    if final_count != 108:
        errors.append(f"Final plan contains {final_count} commands, expected 108.")
    checks["launch_plans"] = {
        "hpo": str(hpo_plan.relative_to(ROOT)),
        "hpo_count": hpo_count,
        "final": str(final_plan.relative_to(ROOT)),
        "final_count": final_count,
        "deprecated_combined": str(deprecated_plan.relative_to(ROOT)),
        "device_env": "DEVICE",
        "retrieval_compute_ceiling_env": ("RETRIEVAL_COMPUTE_CEILING_HOURS"),
    }
    if args.skip_tests:
        errors.append("Executable verification was skipped (--skip-tests).")
    else:
        _check_tests(errors, checks)

    report_path = Path(args.report)
    if not report_path.is_absolute():
        report_path = ROOT / report_path
    _write_report(
        report_path,
        checks,
        errors,
        warnings,
        hpo_plan,
        hpo_count,
        final_plan,
        final_count,
        args.skip_tests,
    )

    print(f"HPO plan: {hpo_plan.relative_to(ROOT)} ({hpo_count} commands)")
    print(f"Final plan: {final_plan.relative_to(ROOT)} ({final_count} commands)")
    print(f"Report: {report_path.relative_to(ROOT)}")
    if errors:
        print("PHASE2_NOT_READY")
        for index, error in enumerate(errors, 1):
            print(f"[{index}] {error}")
        return 1
    if warnings:
        print("READY_FOR_HPO_WITH_RETRIEVAL_WARNING")
        for index, warning in enumerate(warnings, 1):
            print(f"[warning {index}] {warning}")
        return 0
    print("READY_FOR_HPO")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
