#!/usr/bin/env python
"""Phase 2 readiness gate and launch-command generator.

This script does not run HPO or final evaluation. It validates the fixed
protocol, configuration surface, local data, exact dependencies, and smoke
tests. READY_FOR_HPO is printed only when every check succeeds.
"""

import argparse
from importlib import metadata
import json
from pathlib import Path
import subprocess
import sys

import yaml


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.data.adapters import (  # noqa: E402
    ADAPTER_REGISTRY,
    DAFV2Adapter,
    ModernNCAAdapter,
    NativeRawAdapter,
    RTDLQuantileAdapter,
    TabMAdapter,
    TabMPLEAdapter,
    TabRAdapter,
)
from src.hpo.schema import load_search_space  # noqa: E402
from src.native.dependencies import DEPENDENCIES, dependency_report  # noqa: E402
from src.phase2_execution import NATIVE_MODELS  # noqa: E402
from src.phase2_protocol import (  # noqa: E402
    DATASETS,
    FINAL_EVALUATION_SEEDS,
    HPO_SEED,
    MAIN_METHODS,
    MAIN_RANK_INCLUDED,
    N_HPO_COMPLETE_TRIALS,
    PROTOCOL_VERSION,
    SECONDARY_METHODS,
)


TUNABLE_METHODS = tuple(
    method for method in MAIN_METHODS + SECONDARY_METHODS if method != "tabicl"
)
ALL_METHODS = MAIN_METHODS + SECONDARY_METHODS
SEARCH_ROOT = ROOT / "configs/hpo/phase2"
BASE_ROOT = ROOT / "configs/experiments/phase2/base"


def _read_yaml(path):
    with Path(path).open(encoding="utf-8") as file:
        return yaml.safe_load(file) or {}


def _command_for_hpo(dataset, model):
    best = f"configs/experiments/phase2/{model}/{dataset}_best.yaml"
    return (
        "python runners/run_phase2.py hpo "
        f"--base-config configs/experiments/phase2/base/{dataset}.yaml "
        f"--search-space configs/hpo/phase2/{model}.yaml "
        f"--best-output {best}"
    )


def _command_for_final(dataset, model):
    command = (
        "python runners/run_phase2.py final "
        f"--base-config configs/experiments/phase2/base/{dataset}.yaml "
        f"--search-space configs/hpo/phase2/{model}.yaml"
    )
    if model != "tabicl":
        command += f" --best-config configs/experiments/phase2/{model}/{dataset}_best.yaml"
    return command


def launch_commands():
    commands = []
    for dataset in DATASETS:
        for model in ALL_METHODS:
            if model != "tabicl":
                commands.append(_command_for_hpo(dataset, model))
            commands.append(_command_for_final(dataset, model))
    return commands


def write_launch_plan(path):
    path = Path(path)
    if not path.is_absolute():
        path = ROOT / path
    commands = launch_commands()
    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        "# Generated by analysis/phase2_preflight.py. Review before running.",
        "# This file contains commands only; generation never launches experiments.",
        "",
    ]
    for dataset in DATASETS:
        lines.append(f"# Dataset: {dataset}")
        for model in ALL_METHODS:
            if model != "tabicl":
                lines.append(_command_for_hpo(dataset, model))
            lines.append(_command_for_final(dataset, model))
        lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    path.chmod(0o755)
    return path, len(commands)


def _check_protocol(errors, checks):
    expected_seeds = tuple(range(43, 58))
    checks["protocol_version"] = PROTOCOL_VERSION
    checks["hpo_seed"] = HPO_SEED
    checks["final_seeds"] = list(FINAL_EVALUATION_SEEDS)
    checks["hpo_complete_trials"] = N_HPO_COMPLETE_TRIALS
    if HPO_SEED != 42:
        errors.append(f"HPO seed must be 42, got {HPO_SEED}.")
    if FINAL_EVALUATION_SEEDS != expected_seeds:
        errors.append("Final seed registry must be exactly 43..57.")
    if N_HPO_COMPLETE_TRIALS != 50:
        errors.append("HPO target must be 50 valid COMPLETE trials.")
    expected_main = {
        "daf_moe_v2", "xgboost", "catboost", "mlp", "resnet",
        "ft_transformer", "tabr", "tabm", "modernnca", "realmlp", "tabicl",
    }
    if set(MAIN_METHODS) != expected_main or len(MAIN_METHODS) != 11:
        errors.append("Main method registry is not the fixed set of 11 methods.")
    if SECONDARY_METHODS != ("tabm_ple",):
        errors.append("TabM PLE must be the only secondary method.")
    for method in ALL_METHODS:
        expected = method != "tabm_ple"
        if MAIN_RANK_INCLUDED.get(method) is not expected:
            errors.append(f"main-rank metadata mismatch for {method}.")


def _check_configs(errors, checks):
    expected_spaces = {f"{method}.yaml" for method in ALL_METHODS}
    actual_spaces = {path.name for path in SEARCH_ROOT.glob("*.yaml")}
    if actual_spaces != expected_spaces:
        errors.append(
            "Search-space files mismatch: "
            f"missing={sorted(expected_spaces - actual_spaces)}, "
            f"extra={sorted(actual_spaces - expected_spaces)}."
        )
    parsed = {}
    for method in ALL_METHODS:
        path = SEARCH_ROOT / f"{method}.yaml"
        if not path.exists():
            continue
        try:
            space = load_search_space(path)
        except Exception as exc:
            errors.append(f"Invalid search space {path}: {exc}")
            continue
        parsed[method] = space.schema_hash
        if space.model_name != method:
            errors.append(f"{path} routes to {space.model_name}, expected {method}.")
        if space.rank_included is not MAIN_RANK_INCLUDED[method]:
            errors.append(f"{path} rank_included is inconsistent with protocol.")
        if method == "tabicl" and space.search:
            errors.append("TabICLv2 must not expose an HPO search section.")
        if method != "tabicl" and not space.search:
            errors.append(f"Tunable method {method} has no search parameters.")
    checks["search_space_hashes"] = parsed

    base_records = {}
    for dataset in DATASETS:
        base_path = BASE_ROOT / f"{dataset}.yaml"
        if not base_path.exists():
            errors.append(f"Missing base config: {base_path.relative_to(ROOT)}")
            continue
        base = _read_yaml(base_path)
        missing = sorted(
            {"data_config_path", "task_type", "optimize_metric"}.difference(base)
        )
        if missing:
            errors.append(f"{base_path} is missing {missing}.")
            continue
        data_path = ROOT / base["data_config_path"]
        if not data_path.exists():
            errors.append(f"Missing dataset config: {base['data_config_path']}")
            continue
        data = _read_yaml(data_path)
        csv_path = ROOT / data.get("csv_path", "")
        if not csv_path.is_file():
            errors.append(f"Missing raw CSV for {dataset}: {csv_path}")
        base_records[dataset] = {
            "task_type": base["task_type"],
            "metric": base["optimize_metric"],
            "data_config": base["data_config_path"],
            "csv": str(csv_path.relative_to(ROOT)) if csv_path.exists() else str(csv_path),
        }
    checks["datasets"] = base_records


def _check_routing(errors, checks):
    expected_adapters = {
        "daf_moe_v2": DAFV2Adapter,
        "mlp": RTDLQuantileAdapter,
        "resnet": RTDLQuantileAdapter,
        "ft_transformer": RTDLQuantileAdapter,
        "tabr": TabRAdapter,
        "tabm": TabMAdapter,
        "tabm_ple": TabMPLEAdapter,
        "modernnca": ModernNCAAdapter,
        "xgboost": NativeRawAdapter,
        "catboost": NativeRawAdapter,
        "realmlp": NativeRawAdapter,
        "tabicl": NativeRawAdapter,
    }
    for model, expected in expected_adapters.items():
        actual = ADAPTER_REGISTRY.get(model)
        if actual is not expected:
            errors.append(
                f"Adapter routing mismatch for {model}: "
                f"{getattr(actual, '__name__', actual)} != {expected.__name__}."
            )
    if NATIVE_MODELS != frozenset({"xgboost", "catboost", "realmlp", "tabicl"}):
        errors.append("Native execution registry does not match the protocol.")
    native_sources = [
        ROOT / "src/native/data.py",
        ROOT / "src/native/runner.py",
        ROOT / "src/native/estimators.py",
        ROOT / "runners/run_phase2_native.py",
    ]
    for path in native_sources:
        if "DAFPreprocessor" in path.read_text(encoding="utf-8"):
            errors.append(f"Native path imports or mentions DAFPreprocessor: {path}")
    checks["adapter_routing"] = {
        model: adapter.__name__ for model, adapter in expected_adapters.items()
    }


def _installed_version(distribution):
    try:
        return metadata.version(distribution)
    except metadata.PackageNotFoundError:
        return None


def _check_dependencies(errors, checks):
    python_version = f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}"
    checks["python_version"] = python_version
    if sys.version_info[:2] < (3, 10):
        errors.append(
            f"Phase 2 requires Python >=3.10 for the full model set; current={python_version}."
        )

    optuna = _installed_version("optuna")
    checks["optuna"] = {"required": "4.9.0", "installed": optuna}
    if optuna != "4.9.0":
        errors.append(
            f"Optuna pin mismatch: installed={optuna}, required=4.9.0. "
            "Run: python -m pip install 'optuna==4.9.0'"
        )

    native = {}
    for model in DEPENDENCIES:
        report = dependency_report(model)
        native[model] = report
        if not report["compatible"]:
            errors.append(
                f"{model} dependency is not ready: installed="
                f"{report['installed_version']}, required={report['required_version']}, "
                f"python>={report['minimum_python']}. Run: {report['install_command']}"
            )
    checks["native_dependencies"] = native

    requirements = (ROOT / "requirements.txt").read_text(encoding="utf-8")
    required_lines = ["optuna==4.9.0"] + [
        spec.requirement for spec in DEPENDENCIES.values()
    ]
    for requirement in required_lines:
        if requirement not in requirements:
            errors.append(f"requirements.txt is missing exact pin: {requirement}")


def _run_command(command):
    completed = subprocess.run(
        command,
        cwd=str(ROOT),
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )
    output = completed.stdout.strip()
    tail = "\n".join(output.splitlines()[-20:])
    return {
        "command": " ".join(command),
        "returncode": completed.returncode,
        "output_tail": tail,
    }


def _check_tests(errors, checks):
    commands = (
        [sys.executable, "-m", "unittest", "discover", "-s", "tests", "-v"],
        [sys.executable, "analysis/verify_baselines.py"],
        [sys.executable, "analysis/verify_v2_architecture.py"],
        [sys.executable, "analysis/verify_v15_equivalence.py"],
        [sys.executable, "analysis/verify_phase2_native_models.py"],
    )
    results = []
    for command in commands:
        result = _run_command(command)
        results.append(result)
        if result["returncode"] != 0:
            errors.append(
                f"Verification failed ({result['command']}):\n{result['output_tail']}"
            )
    checks["test_runs"] = results


def _write_report(path, checks, errors, launch_plan, launch_count, tests_skipped):
    payload = {
        "protocol_version": PROTOCOL_VERSION,
        "ready_for_hpo": not errors,
        "tests_skipped": bool(tests_skipped),
        "launch_plan": str(launch_plan.relative_to(ROOT)),
        "launch_command_count": launch_count,
        "checks": checks,
        "blockers": errors,
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(payload, indent=2, sort_keys=True, default=str) + "\n",
        encoding="utf-8",
    )
    return path


def parse_args(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--skip-tests",
        action="store_true",
        help="Skip executable tests. This always prevents a READY result.",
    )
    parser.add_argument(
        "--launch-plan",
        default="scripts/phase2_launch_commands.sh",
        help="Generated command file (commands are not executed).",
    )
    parser.add_argument(
        "--report",
        default="results/phase2/preflight_report.json",
        help="Machine-readable preflight report.",
    )
    return parser.parse_args(argv)


def main(argv=None):
    args = parse_args(argv)
    errors = []
    checks = {}
    _check_protocol(errors, checks)
    _check_configs(errors, checks)
    _check_routing(errors, checks)
    _check_dependencies(errors, checks)
    launch_plan, launch_count = write_launch_plan(args.launch_plan)
    expected_count = len(DATASETS) * (2 * len(TUNABLE_METHODS) + 1)
    if launch_count != expected_count:
        errors.append(
            f"Launch plan contains {launch_count} commands, expected {expected_count}."
        )
    if args.skip_tests:
        errors.append("Executable verification was skipped (--skip-tests).")
    else:
        _check_tests(errors, checks)

    report_path = Path(args.report)
    if not report_path.is_absolute():
        report_path = ROOT / report_path
    _write_report(
        report_path,
        checks,
        errors,
        launch_plan,
        launch_count,
        args.skip_tests,
    )

    print(f"Launch plan: {launch_plan.relative_to(ROOT)} ({launch_count} commands)")
    print(f"Report: {report_path.relative_to(ROOT)}")
    if errors:
        print("PHASE2_NOT_READY")
        for index, error in enumerate(errors, 1):
            print(f"[{index}] {error}")
        return 1
    print("READY_FOR_HPO")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
